export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  CINEMA_OWNER: 'CINEMA_OWNER',
  MOVIE_PROVIDER: 'MOVIE_PROVIDER',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN'
};

export const CINEMA_VERIFICATION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  DOCUMENTS_REQUIRED: 'DOCUMENTS_REQUIRED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED'
};

export const EXHIBITION_AUTHORIZATION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  DOCUMENTS_REQUIRED: 'DOCUMENTS_REQUIRED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
  SUSPENDED: 'SUSPENDED'
};

export const SHOW_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  SOLD_OUT: 'SOLD_OUT',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  SUSPENDED: 'SUSPENDED'
};

export const SHOW_SEAT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  HELD: 'HELD',
  BOOKED: 'BOOKED',
  BLOCKED: 'BLOCKED'
};

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  REFUNDED: 'REFUNDED'
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED'
};

export const QUEUE_STATUS = {
  WAITING: 'WAITING',
  PROMOTED: 'PROMOTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  BOOKED: 'BOOKED',
  SKIPPED: 'SKIPPED'
};

export const RABBITMQ_EXCHANGE = 'tixora.booking';

export const RABBITMQ_ROUTING_KEYS = {
  SEAT_HOLD_CREATED: 'seat.hold.created',
  SEAT_HOLD_EXPIRED: 'seat.hold.expired',
  SEAT_QUEUE_JOINED: 'seat.queue.joined',
  SEAT_QUEUE_PROMOTE: 'seat.queue.promote',
  BOOKING_CREATED: 'booking.created',
  BOOKING_CONFIRMED: 'booking.confirmed',
  BOOKING_CANCELLED: 'booking.cancelled',
  PAYMENT_SUCCESS: 'payment.success',
  PAYMENT_FAILED: 'payment.failed',
  TICKET_GENERATED: 'ticket.generated'
};

export const RABBITMQ_QUEUES = {
  SEAT_EXPIRY: 'tixora.seat.expiry',
  SEAT_QUEUE: 'tixora.seat.queue',
  BOOKING: 'tixora.booking',
  PAYMENT: 'tixora.payment',
  NOTIFICATION: 'tixora.notification'
};
